pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Build and test (ubuntu-20.04)
      - check-success=Build and test (macos-11)
      - check-success=Build and test (windows-2022)
    actions:
      merge:
        method: squash
