name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-20.04
          - os: macos-11
          - os: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:check

      - name: Format
        run: npm run format:check

      - name: Test
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Test
        run: npm test
        if: runner.os != 'Linux'

      - name: Build
        run: npm run compile
